frr defaults traditional
hostname isp-a
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 10.200.1.1/32
exit
!
ip prefix-list LAB-ROUTES seq 10 permit 10.200.1.1/32
ip prefix-list LAB-ROUTES seq 20 permit 10.200.2.1/32
ip prefix-list LAB-ROUTES seq 30 permit 10.200.3.1/32
!
router bgp 65001
 bgp router-id 10.200.1.1
 bgp log-neighbor-changes
 neighbor 10.200.12.3 remote-as 65002
 neighbor 10.200.12.3 description ISP-B
 neighbor 10.200.13.3 remote-as 65003
 neighbor 10.200.13.3 timers 3 9
 neighbor 10.200.13.3 description ISP-C
 !
 address-family ipv4 unicast
  network 10.200.1.1/32
  neighbor 10.200.12.3 prefix-list LAB-ROUTES in
  neighbor 10.200.12.3 prefix-list LAB-ROUTES out
  neighbor 10.200.13.3 prefix-list LAB-ROUTES in
  neighbor 10.200.13.3 prefix-list LAB-ROUTES out
 exit-address-family
exit
!
