frr defaults traditional
hostname isp-c
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 10.200.3.1/32
exit
!
ip prefix-list LAB-ROUTES seq 10 permit 10.200.1.1/32
ip prefix-list LAB-ROUTES seq 20 permit 10.200.2.1/32
ip prefix-list LAB-ROUTES seq 30 permit 10.200.3.1/32
!
router bgp 65003
 bgp router-id 10.200.3.1
 bgp log-neighbor-changes
 neighbor 10.200.13.2 remote-as 65001
 neighbor 10.200.13.2 timers 3 9
 neighbor 10.200.13.2 description ISP-A
 neighbor 10.200.23.2 remote-as 65002
 neighbor 10.200.23.2 description ISP-B
 !
 address-family ipv4 unicast
  network 10.200.3.1/32
  neighbor 10.200.13.2 prefix-list LAB-ROUTES in
  neighbor 10.200.13.2 prefix-list LAB-ROUTES out
  neighbor 10.200.23.2 prefix-list LAB-ROUTES in
  neighbor 10.200.23.2 prefix-list LAB-ROUTES out
 exit-address-family
exit
!
